---
- name: Install and configure Caddy webserver  # Любое описание
  hosts: my_servers  # хосты из файла inventory/hosts, где будем выполнять наш плейбук
  connection: ssh
  become: true

  roles:
    - caddy_deploy  # собственно, роль для выполнения
